### ISSUE TITLE
Recommended hardware

### ISSUE THREAD

**Issue by fulldecent** [64characters/Telephone#122]
This software is amazing and unrivaled.

You recommend using a USB headset for better quality. Can you please recommend specific USB headsets, analog headsets and/or bluetooth headsets you recommend to work best with this software.

Please also let me know your Amazon affiliate ID and I will add these to the webpage as recommendations.

**Comment by visioncode** [comment]
i love this software too .. "Telephone" is the one and only SIP client which works for me with my SIP-Provider Placetel without any problems. I tried 3-4 more Softphones, but it ever ends up in any problems or misfunctionality. Maybe because most of them are focused on windows.

Unfortunately it seems like this app is not focused by the developer anymore. I guess many people would 
pay for it - it should'nt be for free. I hope development continues ..

**Comment by fulldecent** [comment]
Bump

**Comment by fulldecent** [comment]
Would a PR that fixes this be in scope to be merged?

Will a pull request be accepted if it is licensed as CC0?

**Comment by abhibeckert** [comment]
I've had Excellent experience with the wired Antlion Audio microphone and their USB "Sound card".

They also have a wireless Mic now, which I haven't tried but looks excellent. It doesn't use bluetooth, they provide a USB dongle which seems like a good solution after all the trouble I've had with bluetooth Mics.

**Comment by eofster** [comment]
I’m not ready to create a list of supported hardware. Any headset that macOS supports should work. The specific features like reacting to the presses on headset buttons don’t exist yet. If I add such support in the future (which I plan), I will try to come up with a list of supported headsets in this way. But in general, there are no recommendations.
