### ISSUE TITLE
No audio received over split-tunnel OpenVPN connection

### ISSUE THREAD

**Issue by mcdado** [64characters/Telephone#561]
My setup: I'm using Telephone from the MAS on my MacBook, at my home the network is 192.168.34.0/24, while we have a PBX a the office (which network is 192.168.3.0/24) and i'm connecting via an OpenVPN server which lives in that network with address 192.168.3.8, and the OpenVPN network is 10.8.0.0/24.

If I connect to our network in full-tunnel (adding `redirect-gateway def1 bypass-dhcp` to my ovpn file) then there's no problem.

The problem comes when I opt for split-tunnel (not using the above directive): I can make calls and answer them, and while my audio is heard on the other side, I can't hear the audio from the other side. The reason I think it's because the PBX is addressing the RTP packets to my Mac's public IPv4. I say this because I activated the packet capturing on our PBX and analyzed it with Wireshark.

You can see here that when I'm connecting with the VPN (using split tunnel setup) the app is advertising the public IP address:

<img width="1167" alt="Screenshot 2020-03-09 at 02 31 36" src="https://user-images.githubusercontent.com/898057/76175703-1d2e5180-61ae-11ea-8a21-2f90333a48c6.png">

In the following screenshot, you can see a call with a Bria app on my iPhone (10.8.0.6) and Telephone on my Mac (10.8.0.10) both connected over OpenVPN, but the packets are not arriving to my Mac.

<img width="1167" alt="Screenshot 2020-03-09 at 02 32 15" src="https://user-images.githubusercontent.com/898057/76175731-333c1200-61ae-11ea-95e5-583a1c331025.png">

Actually, Bria for iOS and Mac is the only app that I found properly working over OpenVPN in my case. I don't know exactly what they do, I imagine they figure out the route used to establish the connection and use the address on that interface, and their app works flawlessly in this regard. For reference, in their iOS app I choose "Server Managed" as NAT strategy, which is the only mode that works properly.

**Comment by devZer0** [comment]
i know this problem very well, this should probably be fixed by this : https://github.com/64characters/Telephone/pull/556

we are currently using blink lite for home/remote office users via openvpn, that does not suffer from this problem https://apps.apple.com/us/app/blink-lite/id431473881?mt=12

**Comment by devZer0** [comment]
iirc, you can override this problem in bria. you may try using pbx IP adress instead of dns name in configuration. at least in x-lite this workarounded the problem

**Comment by mcdado** [comment]
X-Lite on desktop and Bria on iOS work correctly using the setting “server managed” for NAT traversal. Since they’re moving away from the free offer I was looking for alternatives. Thanks for the tips.

**Comment by devZer0** [comment]
i had a look at their now "cloud bundled" product and i think it sucks. so does their communication behaviour, if you register for download, you are getting spammed until you unsubscribe from the 10 mailing lists they add you to...

**Comment by mcdado** [comment]
Personally I solved the issue server side. I found out that KalliopePBX has a setting on accounts to enable NAT, which basically rewrites the destination IP from the incoming connection. For me that’s enough because the PBX is only accessible locally or through VPN, no need of fancy NAT traversal strategies.

**Comment by eofster** [comment]
Although the changes in #556 should help, it is strange that you were having the public IP address in SDP. The problem I was trying to solve in #556 is when the SDP contains the IP address of your Mac in its local home network, and that’s why you wouldn’t hear anything. The server would try to send RTP packets to an IP address from your home network, but wouldn’t have a route to it. Do you have either STUN or ICE configured in Telephone? If yes, that would explain the public IP address.

Also, if you have STUN or ICE configured in the app, the changes in #556 would not solve the problem, because STUN or ICE setting (server-side NAT traversal) wins over the new checkbox behavior introduced in #556 (client-side NAT traversal). If an IP address is detected using STUN, it will be put to SDP in both the current version and after applying changes in #556.

And in general I’d say that doing all of that on the server is more robust. You won’t depend on different SIP implementation in different hard- or softphones.

**Comment by mcdado** [comment]
Thank you for the insight. Well I probably had turned on ICE because either I read it somewhere, somebody suggested it, or it was the default, I don’t know.

Anyway I was just surprised that none of the suppliers and service providers (one that installed Kalliope PBX and another that setup OpenVPN server and also knows about VoIP) had even suggested to enable NAT on the server. Anyway, ice, stun, dns srv… I’m a bit fuzzy about all this stuff, I understand NAT in a general sense. Now I do more. Thank you.

Anyway, for anybody with a private PBX like us, does it do any harm to have NAT enabled on the server?

**Comment by eofster** [comment]
Well, it probably depends on the PBX. I would try enabling it by default and disabling it on case by case basis. Also, technically, the situation you have is probably not related to NAT directly. But the solution (either to ignore the IP address in SDK or update it there) is the same as for NAT traversal. That’s why it might be confusing for somebody setting it up. They would think that they don’t need this option because there is no NAT involved.

**Comment by mcdado** [comment]
With 1.4.1 from the MAS and NAT disabled on the account (so the PBX doesn't rewrite the IP, it uses the advertised one) it seems to work correctly now! Thank you!

**Comment by eofster** [comment]
And you checked the “Update IP address” checkbox in the advanced account settings, right? It’s on by default for the new accounts, but untouched for the existing ones.

**Comment by mcdado** [comment]
Yes it was in the indeterminate state, I selected it.

**Comment by devZer0** [comment]
yes, it's fixing the problem for me,too. thanks very much.
